### ISSUE TITLE
Walking Dead

### ISSUE THREAD

**Issue by javaplus** [ManApart/quest-command#18] opened 2022-05-14 02:09 UTC
When you die nothing changes except your health is at zero.

**Comment by ManApart** [comment] 2022-05-14 14:52
It seems like death works as intended in single player. I believe that either the server was out of date or I'm missing something. I'll test with the server and see...

**Comment by ManApart** [comment] 2022-05-14 14:55
Yup, I had built and pushed the local jar through the WSL but ran the server outside the WSL, which uses a different maven repo, so the server was not getting the latest jar. Closing this as I believe the issue was manual error on my part.

**Closed by ManApart** 2022-05-14 14:55 UTC
